#!/bin/sh

ARGS="$@"
if [ -z "$ARGS" ]; then
    ARGS="tasks"
fi

DOCKER_IMAGE=sqlite-fts5-build

docker build . -t "${DOCKER_IMAGE}"
touch local.properties.dummy

docker run --rm -it -v "$(pwd):/build" -w /build -u $(id -u):$(id -g) -v "$(pwd)/local.properties.dummy:/build/local.properties" "${DOCKER_IMAGE}"  ./gradlew $ARGS
