#!/bin/sh

ARGS="$@"
if [ -z "$ARGS" ]; then
    ARGS="tasks"
fi

docker_image=sqlite-fts5-build

docker build . -t ${docker_image}
touch local.properties.dummy

docker run \
    --rm \
    -u $(id -u):$(id -g) \
    -v "$(pwd):/build" \
    -v "$(pwd)/local.properties.dummy:/build/local.properties" \
    -w /build \
    -it ${docker_image} \
    ./gradlew $ARGS
